name: dream_pedidos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  bloc: ^8.1.4
  equatable: ^2.0.7
  csv: ^6.0.0
  excel: ^4.0.6
  path: ^1.9.0
  file_picker: ^8.1.7
  flutter_bloc: ^8.1.6
  intl: ^0.20.1
  printing: ^5.13.4
  pdf: ^3.11.1
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.1
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#BA0C2F"  # 🔴 Background color for splash screen
  image: assets/images/logo.png  # ✅ App logo
  android: true
  ios: true
  android_12:
    image: assets/images/logo.png
    color: "#BA0C2F"  # 🔴 Background color for Android 12+

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#BA0C2F"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
